### ISSUE TITLE
Some of the operators are not displayed well in the display

### ISSUE THREAD

**Issue by faatihi** [Chentiwuni/Calculator#1]
The multiplication and division operators are not displayed correctly.
Those symbols should show exactly as seen on their respective buttons.
Don't use asterisk (*) and forward-slash (/) to represent them.

**Comment by Chentiwuni** [comment]
Now 'x' used for multiplication and '÷' used for division instead of '*' and '/'.

**Comment by faatihi** [comment]
Very good on the ÷ symbol.
The multiplication symbol though. It looks like the small letter x.
There is a multiplication symbol. Kindly use that instead.
It will look really better.

**Comment by Chentiwuni** [comment]
Multiplication symbol looking like letter 'x' now '×' .
