### ISSUE TITLE
After first answer, subsequent answer is sometimes wrong

### ISSUE THREAD

**Issue by faatihi** [Chentiwuni/Calculator#2]
The answer is always correct the first time.
But when you follow it up with an operator to continue the calculation, the next answer is sometimes wrong.

Forexample (steps):
1. Type **78+2=**
2. The answer is **80**, which is correct
3. Then type **x2=**
4. The answer displays **82**, instead of **160**
5. The user expects that the 80 be multiplied by the 2.

**Comment by Chentiwuni** [comment]
Answers not being correct sometimes after following the initial answer with an operator solved.

**Comment by faatihi** [comment]
you can close this issue now.
once a client confirms that the issue has been resolved, it is safe to close it.
